### ISSUE TITLE
Ejecutando los test sin IDE

### ISSUE THREAD

**Issue by paulinohuerta** [Juandelsal/ProyectoTP1Ev3#1]
Hola,

Podrías agregar las instrucciones para construir el proyecto y ejecutar todos los test de forma automatizada, sin uso de cualquier IDE, es decir invocando a la JVM desde la línea de comandos.

Muchas gracias

**Comment by JuandeLS3** [comment]
@paulinohuerta Añadido al README.MD, gracias!
